include ./current-theme.conf

font_family JetBrainsMono Nerd Font Mono
font_style SemiBold
bold_font_style Bold
italic_font_style Italic
bold_italic_font_style Bold Italic

symbol_map U+1F300-U+1FAFF Noto Color Emoji

