include ./current-theme.conf

# Font 
font_family JetBrainsMono Nerd Font Mono
font_style SemiBold
bold_font_style Bold
italic_font_style Italic
bold_italic_font_style Bold Italic

background_opacity 0.9
background_blur 20

symbol_map U+1F300-U+1FAFF Noto Color Emoji

# Zoom in (Ctrl + +)
map ctrl+kp_add change_font_size all +2.0

# Zoom out (Ctrl + -)
map ctrl+minus change_font_size all -2.0

# Reset font size (Ctrl + 0, optionnel mais utile)
map ctrl+0 change_font_size all 0

