#  _    _ _   _
# | | _(_) |_| |_ _   _
# | |/ / | __| __| | | |
# |   <| | |_| |_| |_| |
# |_|\_\_|\__|\__|\__, |
#                 |___/
include ./current-theme.conf

shell /bin/bash -l

########
# FONT #
########
font_family 'BerkeleyMono Nerd Font Mono'
font_style SemiBold
bold_font SemiBold
italic_font SemiBold Oblique
bold_italic_font SemiBold Oblique
font_size 18

background_opacity 0.9
background_blur 20

symbol_map U+1F300-U+1FAFF Noto Color Emoji

# Zoom in (Ctrl + +)
map ctrl+kp_add change_font_size all +2.0

# Zoom out (Ctrl + -)
map ctrl+minus change_font_size all -2.0

