# Généré automatiquement par wal
set -g @tmux-dotbar-fg "#c0c3c1"
set -g @tmux-dotbar-bg "#061008"
set -g @tmux-dotbar-fg-current "#01D3CE"
set -g @tmux-dotbar-fg-session "#c0c3c1"
set -g @tmux-dotbar-fg-prefix "#01D3CE"
