name: log-dev
root: ~/code/lq/elk/

startup_pane: 1
enable_pane_titles: true

windows: 
  - editor:
      layout: main-vertical
      panes:
        - nvim
  - docker-compose:
      layout: main-vertical
  - logs:
      layout: main-vertical
      panes:
        - logstash:
            null
        - edit:
            null
